### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mtdudek** [JackyyTV/IntegrationForegoing#1]
Hi.
Is it intended for plant recollector to chop down whole hemp plant?
Shouldn't it break only top part?
thanks

**Comment by JackyyTV** [comment]
That is intended, since the Plant Recollector works differently, you'll have to use the Planter to replant the seeds like how other plants works.

**Comment by mtdudek** [comment]
Would you mind putting this to config file?

2017-09-15 20:54 GMT+02:00 Jacky Scrubby <notifications@github.com>:

**Comment by JackyyTV** [comment]
I could, but it'll stay disabled by default as it might cause some other issues.

**Comment by mtdudek** [comment]
That is fine with me

**Comment by JackyyTV** [comment]
I've added a config option for this in commit 0f10d01, the new update with that commit will hopefully be out soon.
