### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by trilexcom** [JackyyTV/IntegrationForegoing#12]
hi Jacky 

i am getting this error msg in console

KnightMiner from TContruct told me open a issue with you.

this is what he says 

This looks like integrationforegoing's fault, they are accessing our traits before we have a chance to register the potions (thus it is reigstered during their time). Report the issue to that mod's author.

@bookerthegeek we do not register anything into the Minecraft domain, potions are registered under TConstruct.

https://github.com/SlimeKnights/TinkersConstruct/issues/3268

17:02:53 FML main * Dangerous alternative prefix tconstruct for name enderference, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitEnderference.(TraitEnderference.java:18)
17:02:53 FML main * at slimeknights.tconstruct.tools.TinkerTraits.(TinkerTraits.java:72)
17:02:53 FML main * at me.jacky1356400.integrationforegoing.compat.TConstructCompat.preInit(TConstructCompat.java:24)...
17:02:53 FML main ****************************************
17:02:53 FML main ****************************************
17:02:53 FML main * Dangerous alternative prefix tconstruct for name insatiable, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitInsatiable.(TraitInsatiable.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.TinkerTraits.(TinkerTraits.java:78)...
17:02:53 FML main ****************************************
17:02:53 FML main ****************************************
17:02:53 FML main * Dangerous alternative prefix tconstruct for name magnetic, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitMagnetic$MagneticPotion.(TraitMagnetic.java:46)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitMagnetic.(TraitMagnetic.java:25)...
17:02:53 FML main ****************************************
17:02:53 FML main ****************************************
17:02:53 FML main * Dangerous alternative prefix tconstruct for name momentum, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitMomentum.(TraitMomentum.java:18)
17:02:53 FML main * at slimeknights.tconstruct.tools.TinkerTraits.(TinkerTraits.java:83)...
17:02:53 FML main ****************************************
17:02:53 FML main ****************************************
17:02:53 FML main * Dangerous alternative prefix tconstruct for name dot, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitSharp$DoT.(TraitSharp.java:51)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitSharp.(TraitSharp.java:18)...
17:02:53 FML main ****************************************
17:02:53 FML main ****************************************
17:02:53 FML main * Dangerous alternative prefix tconstruct for name splinter, expected integrationforegoing invalid registry invocation/invalid name?
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
17:02:53 FML main * at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:20)
17:02:53 FML main * at slimeknights.tconstruct.library.potion.TinkerPotion.(TinkerPotion.java:13)
17:02:53 FML main * at slimeknights.tconstruct.tools.traits.TraitSplintering.(TraitSplintering.java:14)
17:02:53 FML main * at slimeknights.tconstruct.tools.TinkerTraits.(TinkerTraits.java:92)...
17:02:53 FML main ****************************************

We are using Forge 2556
TinkersContruct Version : TConstruct-1.12-2.7.4.34
MC : 1.12.2
Crashlog : https://pastebin.com/NWMF4wvg

Thanks

Mat

**Comment by JackyyTV** [comment]
I've looked into this, due to the way how Tinkers traits have to be accessed and because this doesn't really cause any major problems, there's no way of fixing this.
