### ISSUE TITLE
[Suggestion] MooFluids integration for Animal Rancher

### ISSUE THREAD

**Issue by brisingraerowing** [JackyyTV/IntegrationForegoing#15]
I use the [Moo Fluids](https://minecraft.curseforge.com/projects/moo-fluids) mod, and having the Animal Rancher able to milk them would be useful, similar to what the Ranchable Fluid Cows mod does for Moo Fluids and MFR on 1.7.10 and 1.10.2.

**Comment by JackyyTV** [comment]
Same with #11, since there's no ways of changing what the Animal Rancher can do via API yet, I'll put this issue on hold for now until it's possible.

**Comment by Buuz135** [comment]
It should work, have you tried it?

**Comment by JackyyTV** [comment]
Is it? I wasn't informed so I didn't know.

**Comment by JackyyTV** [comment]
Should be working in Industrial Foregoing 1.12.2-1.5.11-100 and later.

**Comment by rlnt** [comment]
Still doesn't work
