### ISSUE TITLE
Plant Gatherer integration with Simple Corn

### ISSUE THREAD

**Issue by tgstyle** [JackyyTV/IntegrationForegoing#17]
Industrial Foregoing Version: 1.12.2-1.6.3-107
Integration Foregoing: 1.12-1.4
TeslaCoreLib Version: 1.12-1.0.12
Simple Corn Version: 1.12-2.3.5

The Plant Sower places corn without issue, however the Plant Gatherer does not want to harvest them. Could this be added?

**Comment by JackyyTV** [comment]
I have tried adding Plant Gatherer support for Simple Corn, but unfortunately, it just doesn't work as intended (the corn drops the items on the floor regardless which block is harvested). I have tried contacting the author of Simple Corn but didn't get a response at all. So I am unable to add Plant Gatherer support for Simple Corn for now. However, I have added support so corn seeds can go in Bioreactor.
