### ISSUE TITLE
Tree planter / Harvester

### ISSUE THREAD

**Issue by OrionU** [JackyyTV/IntegrationForegoing#18]
Ive been playing on FTB Direwolf version 1.4.0 and both machines dont work, they have an output, they have power, they do make the sound of harvesting, but they dont actually plant / harvest anything.

**Comment by JackyyTV** [comment]
That's a bug with Industrial Foregoing itself. Please report that to [Industrial Foregoing's issue tracker](https://github.com/Buuz135/Industrial-Foregoing/issues), this repo is dedicated for the addon, not the main mod.
