### ISSUE TITLE
Crashing with latest version. Mob Imprisonment Tool.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [JackyyTV/IntegrationForegoing#19]
industrialforegoing-1.12.2-1.6.5-112.jar

https://hastebin.com/tudedozone.cs

**Comment by JackyyTV** [comment]
That should be reported to [Industrial Foregoing's issue tracker](https://github.com/Buuz135/Industrial-Foregoing/issues) as it's not a crash with Integration Foregoing.

**Comment by Unrepentant-Atheist** [comment]
Woops, my bad. Sorry.
