### ISSUE TITLE
Hemp

### ISSUE THREAD

**Issue by mtdudek** [JackyyTV/IntegrationForegoing#2]
shouldn't it be?
 public List<ItemStack> doHarvestOperation(World world, BlockPos pos, IBlockState blockState) {
        NonNullList<ItemStack> stacks = NonNullList.create();
        if (Config.hempHarvestBothBlocks) {
            blockState.getBlock().getDrops(stacks, world, new BlockPos(pos.getX(), pos.getY() + 1, pos.getZ()), blockState, 0);
            blockState.getBlock().getDrops(stacks, world, pos, blockState, 0);
            world.setBlockToAir(new BlockPos(pos.getX(), pos.getY() + 1, pos.getZ()));
            world.setBlockToAir(pos);
        } else {
             **# blockState.getBlock().getDrops(stacks, world, new BlockPos(pos.getX(), pos.getY() + 1, pos.getZ()), blockState, 0);**
            world.setBlockToAir(new BlockPos(pos.getX(), pos.getY() + 1, pos.getZ()));
        }
        return stacks;
    }

**Comment by JackyyTV** [comment]
1. A bit too late, I already push the new version out.
2. If you want to change anything regarding codes, please do pull requests instead.
3. I know what I am doing, it does really matter to be honest.
https://github.com/Jacky1356400/IntegrationForegoing/blob/8707160e56a56542da10364694df9cb0cb99fd23/src/main/java/me/jacky1356400/integrationforegoing/handler/plant/immersiveengineering/CropHempPlantRecollectable.java#L32-L33
Yes, I can get the drop of the top block instead, but again, it doesn't matter.
