### ISSUE TITLE
Integration with Rustic

### ISSUE THREAD

**Issue by milibucket** [JackyyTV/IntegrationForegoing#21]
I would like to request for integration with plants from rustic mod, as of now the plant gatherer would not collect any crops from the mod, from grapes to herbs.

**Comment by JackyyTV** [comment]
Sorry for the delay with the update, but this is added in [1.6](https://minecraft.curseforge.com/projects/integration-foregoing/files/2546385)!

**Comment by milibucket** [comment]
Than you!
