### ISSUE TITLE
Enable use of IF fertilizer in IE Garden Cloche

### ISSUE THREAD

**Issue by unikmhz** [JackyyTV/IntegrationForegoing#23]
Immersive Engineering's Garden Cloche can't use IF's fertilizer. It would be nice if it did ;)
Issue cross-reference: BluSunrize/ImmersiveEngineering#2913

**Comment by JackyyTV** [comment]
Added in [1.6](https://minecraft.curseforge.com/projects/integration-foregoing/files/2546385).
