### ISSUE TITLE
[Suggestion] Integration for Silent's Gems

### ISSUE THREAD

**Issue by OmegaPaladin** [JackyyTV/IntegrationForegoing#24]
Bioreactor Entries:  Fluffy Puff Seeds  (This would be very useful, as you can easily get stacks and stacks of them)   https://github.com/SilentChaos512/SilentGems/blob/1.12/common/net/silentchaos512/gems/item/ItemFluffyPuffSeeds.java

Laser Drill Entries:  Chaos Essence Ore & Ender Essence Ore (Entries  for the gem ores should be a config option if it is added at all, there are dozens of them) 
https://github.com/SilentChaos512/SilentGems/blob/1.12/common/net/silentchaos512/gems/block/BlockEssenceOre.java

I'm currently working on adding this with a crafttweaker script, but having official support would be great.

**Comment by JackyyTV** [comment]
It's all added in [1.7](https://minecraft.curseforge.com/projects/integration-foregoing/files/2574626) now.
Do note that I have added Laser Drill entries for every single gem ores and the essence ores, feel free to use CraftTweaker for disabling any entries that you don't want.
