### ISSUE TITLE
[Chickens / Hatchery] Include Chicken Manure in the Plant Fertilizer

### ISSUE THREAD

**Issue by EivindAntonsen** [JackyyTV/IntegrationForegoing#25]
Currently, in an automated setup with Industrial Foregoing and Chickens / Hatchery / More Chickens I can not use the main source of fertilizing material (Chicken Manure). Could this be added?

**Comment by JackyyTV** [comment]
There's currently no APIs on Industrial Foregoing for the Plant Fertilizer, but I can get that sorted.

**Comment by EivindAntonsen** [comment]
Awesome. Will that come as a new release, or something I should change on my end?

**Comment by JackyyTV** [comment]
There will be a new version of Industrial Foregoing adding the API first, once that update is released, I will be able to add the integration on my side using the API and then a new version of Integration Foregoing will be released. You don't have to change anything on your end, just make sure to keep both mods up-to-date. I will be closing this issue once the integration is added, so don't worry. :)

**Comment by JackyyTV** [comment]
Apparently this has been added via allowing the `fertilizer` OreDict to be used, so I don't have to do anything on my side I guess.
Buuz135/Industrial-Foregoing@a152b73

**Comment by EivindAntonsen** [comment]
Sadly this still does not work (chicken manure doesn't count as a fertilizer I guess). Should I maybe take this to Industrial Foregoing instead of Integration?

**Comment by JackyyTV** [comment]
You should do if it doesn't work, since my addon can only help with integrations that are able to be added via the API.
