### ISSUE TITLE
linux compatibility

### ISSUE THREAD

**Issue by Sakata-MC** [JackyyTV/IntegrationForegoing#26]
in linux the configuration files can be duplicated or ignored due to case.
IntegrationForegoing
vs
integrationforegoing

Please make all references to the file the same case, so that windows and linux clients both see the same things.

**Comment by JackyyTV** [comment]
On newer versions of the mod, the mod has switched to use the correctly cased file (`IntegrationForegoing.cfg`), so the lowercase one is no longer being used, just delete it as it won't affect anything at all. Thank you.
