### ISSUE TITLE
[Suggestion] Integration for Agricraft

### ISSUE THREAD

**Issue by kriNon** [JackyyTV/IntegrationForegoing#27]
Any chance of adding support for Agricraft crop sticks to the Plant Gatherer?

1.7.10 Minefactory Reloaded had support for Agricraft Crops but it seems like this support was never implemented in Industral Foregoing.

Thanks!

**Comment by JackyyTV** [comment]
That was actually being requested in the Discord server, and I am planning to add support in the next version.

**Comment by kriNon** [comment]
Ah awesome! Super excited!

**Comment by JackyyTV** [comment]
Added in [1.7](https://minecraft.curseforge.com/projects/integration-foregoing/files/2574626).
