### ISSUE TITLE
Rurtic Marsh Mallow Root

### ISSUE THREAD

**Issue by Ostert** [JackyyTV/IntegrationForegoing#28]
The plant gatherer is harvesting the Rurtic Marsh Mallow Root, but i'm not getting any drops. IntegrationForegoing 1.7 Industrial-Foregoing 1.10.0.
Edit: Same issue with Ginseng and Cloudbuff. Common thing is that they are all edible..

**Comment by JackyyTV** [comment]
Found the problem, will be fixed in version 1.7.1 of Integration Foregoing.

**Comment by Ostert** [comment]
Cool, any estimate on when that will be?

**Comment by JackyyTV** [comment]
Most likely tomorrow, just need to add a few more changes and it's ready.

**Comment by Ostert** [comment]
Sweet! Thank you. :)

**Comment by JackyyTV** [comment]
FIxed in [1.7.1](https://minecraft.curseforge.com/projects/integration-foregoing/files/2577315).
