### ISSUE TITLE
Latest agricraft build not working with plant gatherer

### ISSUE THREAD

**Issue by tyggna** [JackyyTV/IntegrationForegoing#29]
agricraft-2.12.0-1.12.0-a5
IntegrationForegoing-1.12.2-1.10.2-178
IndustrialForegoing-1.12.2-1.7.1
minecraft-1.12.2
forge-1.12.2-14.23.4.2705

Multiplayer server, only mod updated since world gen was agricraft

The plant gatherer was working on a field before a server reset, and it hasn't worked since.  It doesn't work on this latest build of agricraft at all.  Resetting the block doesn't change anything and it acts like no plants are there to be harvested.

**Comment by JackyyTV** [comment]
Seems like AgriCraft has done some changes on their side to cause the integration breaking, will fix that ASAP.

**Comment by JackyyTV** [comment]
Fixed in [1.7.2](https://minecraft.curseforge.com/projects/integration-foregoing/files/2581909).

**Comment by tyggna** [comment]
Wow, nice turn around time!

I tested it on my server.   Against resource crops and there's no apparent change in behavior with that new build.  I'll test against other crops and see if it's a config issue.

**Comment by JackyyTV** [comment]
I've tested it myself in my dev environment before pushing out the update and it worked just fine, so if it still doesn't work. it could be something else breaking the integration.

**Comment by tyggna** [comment]
Yeah, you're probably right.  Agricraft has been having issues with Mekanism in my logfiles so I'll dig there.

Here's the full modpack I'm working on, in case you want to look at it or have any insights:  https://www.technicpack.net/modpack/tyggaming.1256710

**Comment by JackyyTV** [comment]
Would be great if you can provide the log file here instead, then I'll be able to see the exact error stacktraces and such.

**Comment by tyggna** [comment]
I wish I could but the logs aren't offering any tracebacks or hints at the problem.

**Comment by JackyyTV** [comment]
Hmm, I am not sure then, it might just be that particular pack's problem. I'll see if anyone else have the same problem first and see what I can do.

**Comment by tyggna** [comment]
It was a config problem, regenerating the agricraft config files fixed it.

**Comment by tyggna** [comment]
Problem still persists on multiplayer dedicated server

**Comment by JackyyTV** [comment]
@Buuz135 got any ideas of what's going on?

**Comment by Buuz135** [comment]
It works perfectly, are you sure @tyggna that you setup your machines properly?

**Comment by tyggna** [comment]
It does work perfectly on a fresh save, just not on a save file that predates the last patch.  I can import stuff into a new world and all, I'm just hoping I don't have to.

**Comment by Buuz135** [comment]
Then its agricraft fault not Integration Foregoing

**Comment by tyggna** [comment]
Alright, cool, thanks for all your help!

**Comment by tyggna** [comment]
Hmm, sorry to bug you again, but even on a fresh world it breaks after a few hours of use.  I'm not sure what event triggers the break, but I suspect it has to do with the range upgrade addons that you can put in the gatherer.
