### ISSUE TITLE
Add support for SimpleHarvest

### ISSUE THREAD

**Issue by MarioAndWeegee3** [JackyyTV/IntegrationForegoing#33]
The mod SimpleHarvest allows you to harvest any crop by right-clicking. The plant interactor is supposed to pick up the drops from crops, but it doesn't with crops that have been modified by SimpleHarvest.

**Comment by JackyyTV** [comment]
Hey @Buuz135 wanna have a look into that?

**Comment by Buuz135** [comment]
Simply Harvest fault that drops items in the ground instead of giving them to the player
