### ISSUE TITLE
[Bug] Liquid XP into Black Hole Tank

### ISSUE THREAD

**Issue by PotatoFlavour** [JackyyTV/IntegrationForegoing#34]
Hi,

I'm playing on a multicraft server with a friend. The server has FTB Revelation 2.5.0 running.

For a couple of weeks I've been trying to find a solution for a compact XP storage instead of spamming tanks through my basement. I figured the best solution is to get Liquid XP into a Black Hole Tank. I thought of this solution 3 versions of FBT ago. Since then, after every update I once again tried to insert Liquid XP into a Black Hole Tank. Unfortunately, it always resulted in the same bug: server crash. I tried to insert it with a Bucket of Liquid XP. I figured if I'd try an automated way we might not be able to get the server running again, because every time it crashed, we had to run "Remove erroring tile entities" in order to fix it. I've tried the same in single player and for some reason it worked. So it seems to be only crashing multiplayer servers.

I figured I wouldn't be the only one struggling with this so I just assumed it would be fixed in next updates, but since it still hasn't, I decided to finally address it. I hope I've been clear enough in order to be able to create a solution for this. If you have any questions I'll try to answer them. If you need any versions please explain where I can find which versions I'm using.

Edit: the Liquid XP Bucket is from Open Blocks, by the way, but since the Black Hole Tank is the only container (that I know of) not being compatible, I decided to address it here.

**Comment by JackyyTV** [comment]
Please note that this repo is for Industrial Foregoing's ADDON, not the base mod itself. Since that issue is related to the base mod itself and has nothing to do with the addon, you should open the issue on Industrial Foregoing's [issue tracker](https://github.com/Buuz135/Industrial-Foregoing/issues) instead. Thank you for understanding.
