### ISSUE TITLE
Crash on loading 

### ISSUE THREAD

**Issue by Rongmario** [JackyyTV/IntegrationForegoing#35]
https://paste.dimdev.org/gefuxejufo.mccrash

Could it be because of me updating IF?

**Comment by JackyyTV** [comment]
Duplicate of #32 and #31.
You're on version 1.7.1 of Integration Foregoing, update to the [latest version (1.7.4)](https://minecraft.curseforge.com/projects/integration-foregoing/files/2610225) fixes the problem.
