### ISSUE TITLE
Crash on load. 

### ISSUE THREAD

**Issue by kwind4444** [JackyyTV/IntegrationForegoing#41]
So, I was using Lapito's Galacticraft 2.1.2. (in ATLauncher), which includes Industrial Foregoing. I tried to load the game multiple times, and whenever FML got to the step where it loaded your mod, the game window changed to a crash report/link to a pastebin. I don't know what the problem is since it never specifies, but here's the link to the dump. https://paste.dimdev.org/ejitozexoc.mccrash

I can provide any information you need, but I'm sure most of it is in that pastebin. For the meantime, I'll have to disable the mod. Love the features, but I obviously can't play the modpack with it. Thank you!

**Comment by kwind4444** [comment]
wait this is for the addon isnt it...
sorry

**Comment by JackyyTV** [comment]
That seems like a bug with Industrial Foregoing, nothing to do with my addon mod, and from what I can see in the crash report, the addon mod isn't even installed anyway.
You should forward that issue to [Industrial Foregoing's repository](https://github.com/Buuz135/Industrial-Foregoing/issues) instead.

**Comment by JackyyTV** [comment]
Ref @ Buuz135/Industrial-Foregoing#542
