### ISSUE TITLE
Cyclic Laser drill enties

### ISSUE THREAD

**Issue by Temenat** [JackyyTV/IntegrationForegoing#44]
I just noticed Cyclic, a well known mod with over 10M downloads that adds a lot of random and useful stuff, needs Laser Drill entries for its Nether and End vanilla ores. This is weird since all other mods with Nether and End vanilla ores have them added to the laser drill entries.
I hope you'll read this and fix it if you can!

**Comment by JackyyTV** [comment]
Added in [1.10](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing/files/2904594).
