### ISSUE TITLE
Silent's Gems Essence Ore Not Working with the Laser Drill

### ISSUE THREAD

**Issue by OmegaPaladin** [JackyyTV/IntegrationForegoing#45]
While the Gem Ores work well with the laser drill, Chaos Essence and Ender Essence Ore do not get harvested.  They are also not in JEI.

They do not show up in the configuration file, and attempting to manually add them does not work.

**Comment by JackyyTV** [comment]
I think I forgot to add them, they will be in the next update coming soon.

**Comment by JackyyTV** [comment]
Fixed in [1.10](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing/files/2904594).
