### ISSUE TITLE
[Suggestion] set preferred ore

### ISSUE THREAD

**Issue by 0ptera** [JackyyTV/IntegrationForegoing#46]
Currently it seems the way to get laser drills to pick a specific ore is to change the oredict entry to that specific ore entry in default_ores.json.
For example to force copper from immersive engineering over thermal foundation and forestry use `immersiveengineering:ore`.

Would it be possible to have a preferredOres setting like in ie and cofh?
```
S:preferredOres <        
        immersiveengineering
        thermalfoundation
        forestry
     >
```

**Comment by JackyyTV** [comment]
You can actually already do that by going go the `config\laser_drill_ores` folder and find the JSON file you would like to edit.
For example, if you prefer to have the Copper Ore from Thermal Foundation, you can modify the entry in `config\laser_drill_ores\default_ores.json`, from this:
![image](https://user-images.githubusercontent.com/11830494/74210354-5b774480-4cc6-11ea-9eff-ae348d9dfa66.png)
To this:
![image](https://user-images.githubusercontent.com/11830494/74210334-4ac6ce80-4cc6-11ea-9a53-95b30084e832.png)
You have full control over each individual entries and tweak them to how you like, no additional support is needed, hope this helps!

(Sorry for the extremely delayed reply, I've been very very busy with work and never got around doing Minecraft stuff.)

**Comment by 0ptera** [comment]
Isn't this just a different place to change the resulting ore.
What I asked for was a way to set an ordered list of mods/ores from which IntegrationForegoing would pick the first available one.

**Comment by JackyyTV** [comment]
That is not actually possible to do in the addon due to limitations in the Industrial Foregoing API and the laser drill entries being written in JSON. It would probably be something that only Industrial Foregoing can implement on their side since all the JSON parsing and processing are done on their side, my addon mod only has access to the API, sorry.

**Comment by 0ptera** [comment]
OK, thanks for clarifying.
