### ISSUE TITLE
Gradle referencing directory that doesn't exist

### ISSUE THREAD

**Issue by josephcsible** [JackyyTV/IntegrationForegoing#5]
https://github.com/Jacky1356400/IntegrationForegoing/blob/7332be286e3f8e3ffaf5a81fc8fd78b8e175dd36/build.gradle#L70

Why do you have this line, but no libs/ directory? It's causing errors about the build path.

**Comment by JackyyTV** [comment]
Not intended, was copied from a Gradle buildscript template that I use for other mods.

**Comment by JackyyTV** [comment]
Also, that might just be an error happens on Linux. I use Windows 10 myself so I am not sure.

**Comment by josephcsible** [comment]
It was actually Eclipse that gave me that error, not Gradle itself.

**Comment by JackyyTV** [comment]
Ah right, but yeah, I use IntelliJ IDEA, so might be different to Eclipse in terms of Gradle buildscript handling.
