### ISSUE TITLE
Plant Gatherer is not running on server

### ISSUE THREAD

**Issue by llFristonJackll** [JackyyTV/IntegrationForegoing#52]
I'm using the direwolf20 modpack at 1.12 as a base and added Integration Foregoing to be able to use the plant gatherer with agricraft, however while on the client it works perfectly when running on server it doesn't work on to harvest vanilla seeds.

What could it be? I was thinking of using the version of the industrial foregoing of PO3, but I don't know if it would work on servers

IntegrationForegoing-1.12.2-1.10

industrialforegoing-1.12.2-1.12.8-232

**Comment by JackyyTV** [comment]
Could be some packet sync issues with dedicated servers, but I am not sure. Do you have a server log I could take a look by any chance? Might help with fixing the bug.

**Comment by JackyyTV** [comment]
Closing this as this appears to be an issue with Industrial Foregoing that has already been fixed, I've already tested this on a server and the Plant Gather was able to harvest AgriCraft crops just fine.
