### ISSUE TITLE
Plant Harvester not working with Rustic Grapes

### ISSUE THREAD

**Issue by cHaOZZoNE** [JackyyTV/IntegrationForegoing#53]
Reproduction: Attempt to use harvester on grapes, either the leaves or the stem does nothing. Machine just works and no output is ever generated.

**Comment by JackyyTV** [comment]
Could be something's changed on Rustic's side, I'll have a look into it.

**Comment by JackyyTV** [comment]
After some investigation, it seems that the Plant Gatherer is seeing the Grape blocks as air blocks, which has completely ignored it while scanning for crops to harvest, and unfortunately, Industrial Foregoing for 1.12 has been discontinued, there's nothing I can do about it in this addon mod.
I'd suggest using the Plant Interactor to harvest the Grapes instead.
