### ISSUE TITLE
Black hole units don’t show up on EU2 indexer

### ISSUE THREAD

**Issue by SlappersOnly** [JackyyTV/IntegrationForegoing#54]
Using the 1.12.2 modpack on technic Platform.
Industrial foregoing 1.12.2-1.12.13
Integration foregoing 1.12.2-1.10

If you connect a black hole unit to the Extra Utilities 2 Indexer and transfer pipes then the items don’t show up on the indexer’s GUI that displays all the items stored.

It does however still pull items from the black hole units if you press the [+] button on a crafting recipe using JEI (just enough items).

Haven’t tested whether it’s the same for the black hole tanks and black hole controllers.

It’s a manageable inconvenience but thought I’d mention it.

**Comment by JackyyTV** [comment]
That issue is not related to this mod as this is just an addon mod for Industrial Foregoing, please submit an issue in [Industrial Foregoing's repository](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues) instead.
