### ISSUE TITLE
Request for Climatic Biomes Pine Tree support

### ISSUE THREAD

**Issue by waitwhereami** [JackyyTV/IntegrationForegoing#55]
[Climatic Biomes](https://github.com/BlackJar72/ClimaticBiomePlacement) adds a Pine tree to the game, which does not seem to work with IF machines. Specifically, the Tree Fluid Extractor doesn't recognize the wood as a valid log. I have integration foregoing installed. I haven't had a chance to try out the Plant Sower or Gatherer to see how they interact with it.

**Comment by JackyyTV** [comment]
Added in [1.11](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing/files/3200529).
