### ISSUE TITLE
[Suggestion] Integration for Advent of Ascension

### ISSUE THREAD

**Issue by zero-breaker** [JackyyTV/IntegrationForegoing#56]
Now that the newest update for [Advent of Ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) added saplings I thought it'd be a good time to suggest this.

The main things would be:
-Plant Gatherer for all types of crops
-Bioreactor for all crop products and saplings
-Laser Drill for all ores
-Straw Drinking for candied water

**Comment by JackyyTV** [comment]
Added in [1.11](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing/files/3200529).

I didn't add any additional entries for Plant Gatherer though as the crops for AoA seem to work just fine with the Plant Gatherer from my own testing.
