### ISSUE TITLE
no yellorite/yellorium being extracted with the laser drill in CJ

### ISSUE THREAD

**Issue by DoomSquirter** [JackyyTV/IntegrationForegoing#57]
Playing Celestial journey. 
industrialforegoing-1.12.2-1.12.13-237
IntegrationForegoing-1.12.2-1.10

JEI shows yellorium with no biome restrictions and a min/max Y level for overworld

5 hours of 3 lasers running with yellow lenses yields zero ore

only thing I noticed is that in the laser drills default_ores.json, I see an entry for oreYellorium, and in game, yellorite ore has 2 oredict entries;
oreYellorite
oreYellorium

**Comment by JackyyTV** [comment]
The default ore entries are generated by Industrial Foregoing, and not my addon, there's really not much I can do about that.
Celestial Journey will have to modify the entry for Yellorium ores and specify an exact ore to use instead of using OreDict, that should fix the problem.

**Comment by DoomSquirter** [comment]
so just fyi, I had this problem in another 1.12 pack but when I ran into the issue, I consulted buuz on how the depth controls work and it has nothing to do with what Y level you place the laser.  if the ore says it's Y=50 then you need to change the depth to 50 no matter where you place it.  This means it might actually be working correctly in CJ but I'm not sure about that.

**Comment by JackyyTV** [comment]
Ah right I see, wasn't aware of the depth controls feature myself but at least now we know it's a feature and not a bug.

**Comment by DoomSquirter** [comment]
well I'm not sure tho.  I don't know if in CJ it shows a depth or not but
if it does, yeah, that's probably the solution right there.
