### ISSUE TITLE
1.2 version check

### ISSUE THREAD

**Issue by Drase333** [JackyyTV/IntegrationForegoing#7]
When trying to start up with the new 1.2 release using minecraft 1.12.1 it stated that it needed minecraft 1.12.2, and the curse page says it should work for all 1.12 releases

**Comment by JackyyTV** [comment]
Oops, I'll fix that real quick.

**Comment by JackyyTV** [comment]
New update is now on [CurseForge](https://minecraft.curseforge.com/projects/integration-foregoing/files/2485771), sorry for the inconvenience.
