### ISSUE TITLE
[Suggestion] Add Plant Recolector / Gatherer support for Ore Shrubs

### ISSUE THREAD

**Issue by ghost** [JackyyTV/IntegrationForegoing#8]
The title says pretty much everything. It'd be a really nice addition to I.F.

**Comment by JackyyTV** [comment]
I have added support for Oreberries already, but I'll add support for that as well on the next update.

**Comment by ghost** [comment]
Alright, thanks! :)

**Comment by Buuz135** [comment]
@Lhykos can you join the discord to help us out? https://discord.gg/Fx6Qz4y

**Comment by JackyyTV** [comment]
Added in 1.3.1.
[Download link](https://minecraft.curseforge.com/projects/integration-foregoing/files/2498409)
