### ISSUE TITLE
[Suggestion] Let the Material StoneWork Factory make Dust if ExNihilo Creatio is present

### ISSUE THREAD

**Issue by ghost** [JackyyTV/IntegrationForegoing#9]
In ExNihilo Creatio you can grind down Sand into Dust. Knowing that the M.S.W.F. can already create Cobblestone, Gravel and Sand, letting it create Dust if ExNihilo Creatio is present would be nice.

**Comment by JackyyTV** [comment]
I asked @Buuz135 and he said he'll add that on his side instead, since there's no API entries for the Material Stonework Factory, plus Sand grinds down to Silicon apparently, so he'll just change that to Dust instead.

**Comment by ghost** [comment]
Oh, alright. I didn't know about Silicon.
Thank you for this, though :)
